services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: production-entry-app
    restart: always
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    depends_on:
      - mysql

  webserver:
    image: nginx:alpine
    container_name: production-entry-nginx
    restart: always
    ports:
      - "8001:80"
    volumes:
      - ./:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  mysql:
    image: mariadb:10.11
    container_name: production-entry-mysql
    restart: always
    environment:
      MYSQL_DATABASE: production_entry
      MYSQL_USER: produser
      MYSQL_PASSWORD: ProdUser@2026
      MYSQL_ROOT_PASSWORD: RootMysql@2026
    volumes:
      - production-entry-mysql-data:/var/lib/mysql
    ports:
      - "3307:3306"

volumes:
  production-entry-mysql-data:
